using Jellyfin.Plugin.SmartLists.Core.Orders;
using Jellyfin.Plugin.SmartLists.Services.Shared;
using MediaBrowser.Controller.Entities;
using MediaBrowser.Controller.Entities.Audio;
using MediaBrowser.Controller.Entities.Movies;
using MediaBrowser.Controller.Entities.TV;

namespace Jellyfin.Plugin.SmartLists.Tests.Core.Orders;

/// <summary>
/// Covers every name/text based sort: <see cref="NameOrder"/> (+Desc) and its
/// <c>NameSortHelper</c>, <see cref="NameIgnoreArticlesOrder"/> (+Desc),
/// <see cref="SeriesNameOrder"/> (+Desc), <see cref="SeriesNameIgnoreArticlesOrder"/> (+Desc)
/// and <see cref="ArtistOrder"/> (+Desc).
///
/// TWO PRECONDITIONS that every test in this file depends on, both properties of Jellyfin's
/// BaseItem rather than of the plugin:
///
/// 1. Reading <c>item.SortName</c> when it was never assigned throws NullReferenceException -
///    the getter falls through to CreateSortName(), which needs a running server. Every item
///    built here therefore gets an EXPLICIT SortName, and "no sort name" is modelled as the
///    empty string (the code under test only ever tests <c>string.IsNullOrEmpty(SortName)</c>,
///    so "" and null are indistinguishable to it - null is simply not reachable in a test).
/// 2. Assigning <c>Name</c> resets the cached sort name, so in every object initializer below
///    Name is assigned BEFORE SortName. Swapping those two lines reintroduces the NRE in (1).
///
/// <c>user</c>, <c>userDataManager</c> and <c>logger</c> are passed as null throughout: none of
/// these orders read them (the only use of logger is a warning on a reflection failure that
/// cannot happen for the types used here).
/// </summary>
public class NameOrderTests
{
    // ---------------------------------------------------------------------------------
    // Item builders. Id is always set: BaseItem.Id defaults to Guid.Empty, so leaving it
    // alone makes every item collide in any Id-keyed lookup.
    // ---------------------------------------------------------------------------------

    private static Movie NewMovie(string? name, string sortName = "") =>
        new() { Id = Guid.NewGuid(), Name = name!, SortName = sortName };

    private static Audio NewAudio(string? name, string sortName = "", string[]? artists = null)
    {
        var audio = new Audio { Id = Guid.NewGuid(), Name = name!, SortName = sortName };
        if (artists is not null)
        {
            audio.Artists = artists;
        }

        return audio;
    }

    private static Episode NewEpisode(string? name, string sortName = "", string? seriesName = null, Guid seriesId = default) =>
        new()
        {
            Id = Guid.NewGuid(),
            Name = name!,
            SortName = sortName,
            SeriesName = seriesName!,
            SeriesId = seriesId,
        };

    private static string[] NamesOf(IEnumerable<BaseItem> items) => items.Select(i => i.Name).ToArray();

    // =================================================================================
    // NameSortHelper - auto-generated SortName detection
    // Audio pattern:   ^\d+\s+-\s+          e.g. "0001 - Track Title"
    // Episode pattern: ^\d{3,}\s+-\s+\d{4,}\s+-\s+   e.g. "001 - 0001 - Title"
    // A match means "Jellyfin generated this, the user asked for Name, so use Name".
    // Anything else is treated as a MANUAL sort title and wins over Name.
    // =================================================================================

    [Theory]
    // Auto-generated shapes -> fall back to Name.
    [InlineData("0001 - Whatever", "Track Name")]
    [InlineData("1 - Whatever", "Track Name")]           // \d+ : a single digit is enough
    [InlineData("12   -   Whatever", "Track Name")]      // \s+ : any run of whitespace
    [InlineData("0001 -\tWhatever", "Track Name")]       // \s+ : tab counts as whitespace
    [InlineData("0001 - ", "Track Name")]                // nothing after the separator
    // Near-misses that must be respected as manual sort titles.
    [InlineData("0001- Whatever", "0001- Whatever")]     // no whitespace before the hyphen
    [InlineData("0001 -Whatever", "0001 -Whatever")]     // no whitespace after the hyphen
    [InlineData("0001 – Whatever", "0001 – Whatever")] // en dash, not a hyphen
    [InlineData("0001 -- Whatever", "0001 -- Whatever")] // double hyphen
    [InlineData(" 0001 - Whatever", " 0001 - Whatever")] // leading space: not anchored at start
    [InlineData("A 0001 - Whatever", "A 0001 - Whatever")]
    [InlineData("Manual Title", "Manual Title")]
    // Empty sort name -> Name.
    [InlineData("", "Track Name")]
    public void GetNameSortValue_Audio_FallsBackToNameOnlyForAutoGeneratedSortNames(string sortName, string expected)
    {
        var audio = NewAudio("Track Name", sortName);

        Assert.Equal(expected, NameSortHelper.GetNameSortValue(audio));
    }

    [Theory]
    // Auto-generated shapes -> fall back to Name.
    [InlineData("001 - 0001 - Whatever", "Pilot")]
    [InlineData("0012   -   00034   -   Whatever", "Pilot")] // 3+ / 4+ digits, \s+ separators
    // Near-misses that must be respected as manual sort titles.
    [InlineData("01 - 0001 - Whatever", "01 - 0001 - Whatever")]   // only 2 leading digits
    [InlineData("001 - 001 - Whatever", "001 - 001 - Whatever")]   // only 3 digits in group 2
    [InlineData("001 - 0001 -Whatever", "001 - 0001 -Whatever")]   // no space after 2nd hyphen
    [InlineData("001 - 0001", "001 - 0001")]                       // second separator missing
    [InlineData("A", "A")]                                         // the documented manual case
    [InlineData("", "Pilot")]
    public void GetNameSortValue_Episode_FallsBackToNameOnlyForAutoGeneratedSortNames(string sortName, string expected)
    {
        var episode = NewEpisode("Pilot", sortName);

        Assert.Equal(expected, NameSortHelper.GetNameSortValue(episode));
    }

    [Fact]
    public void GetNameSortValue_AutoGeneratedPatterns_AreScopedToTheirOwnItemType()
    {
        // The audio pattern is only consulted for Audio and the episode pattern only for
        // Episode, so the very same string is "auto-generated" on one type and a manual sort
        // title on another. A Movie is neither, so it always keeps its SortName.
        Assert.Equal("0001 - Whatever", NameSortHelper.GetNameSortValue(NewMovie("Movie Name", "0001 - Whatever")));
        Assert.Equal("001 - 0001 - Whatever", NameSortHelper.GetNameSortValue(NewMovie("Movie Name", "001 - 0001 - Whatever")));

        // An episode-shaped sort name on an Episode is auto-generated...
        Assert.Equal("Pilot", NameSortHelper.GetNameSortValue(NewEpisode("Pilot", "001 - 0001 - Whatever")));
        // ...but an audio-shaped one on an Episode is not: it fails the 3+/4+ digit pattern.
        Assert.Equal("0001 - Whatever", NameSortHelper.GetNameSortValue(NewEpisode("Pilot", "0001 - Whatever")));
        // The audio pattern is the looser of the two, so it also swallows episode-shaped
        // sort names when the item happens to be Audio.
        Assert.Equal("Track", NameSortHelper.GetNameSortValue(NewAudio("Track", "001 - 0001 - Whatever")));
    }

    [Fact]
    public void GetNameSortValue_NullName_ReturnsEmptyString()
    {
        Assert.Equal("", NameSortHelper.GetNameSortValue(NewAudio(null, "0001 - Gone")));
        Assert.Equal("", NameSortHelper.GetNameSortValue(NewEpisode(null, "001 - 0001 - Gone")));
        Assert.Equal("", NameSortHelper.GetNameSortValue(NewMovie(null)));
    }

    [Fact]
    public void GetNameSortValue_NullItem_ThrowsArgumentNullException()
    {
        Assert.Throws<ArgumentNullException>(() => NameSortHelper.GetNameSortValue(null!));
    }

    // =================================================================================
    // NameOrder / NameOrderDesc
    // =================================================================================

    [Fact]
    public void OrderBy_AudioWithAutoGeneratedSortNames_SortsAlphabeticallyByTitleNotByTrackNumber()
    {
        // The regression this branch exists for: track order is baked into the auto SortName,
        // so honouring it would make "Name Ascending" produce track order instead of A-Z.
        var items = new BaseItem[]
        {
            NewAudio("Zebra", "0001 - Zebra"),
            NewAudio("Apple", "0002 - Apple"),
            NewAudio("Mango", "0003 - Mango"),
        };

        Assert.Equal(["Apple", "Mango", "Zebra"], NamesOf(new NameOrder().OrderBy(items)));
        Assert.Equal(["Zebra", "Mango", "Apple"], NamesOf(new NameOrderDesc().OrderBy(items)));
    }

    [Fact]
    public void OrderBy_ManualSortName_OverridesName()
    {
        var items = new BaseItem[]
        {
            NewAudio("Apple", "zz sorted last"),
            NewAudio("Zebra", "aa sorted first"),
        };

        Assert.Equal(["Zebra", "Apple"], NamesOf(new NameOrder().OrderBy(items)));
        Assert.Equal(["Apple", "Zebra"], NamesOf(new NameOrderDesc().OrderBy(items)));
    }

    [Fact]
    public void OrderBy_UsesNaturalComparer_NumbersNumericallyAndFirst_AndIsCaseInsensitive()
    {
        // SharedNaturalComparer: leading numbers compare numerically, strings that start with
        // a number sort before strings that do not, and the tail compares OrdinalIgnoreCase
        // (so lowercase "apple" precedes "Banana" - plain ordinal would invert that).
        var items = new BaseItem[]
        {
            NewMovie("Banana", "Banana"),
            NewMovie("10 Things", "10 Things"),
            NewMovie("apple", "apple"),
            NewMovie("2 Fast", "2 Fast"),
        };

        Assert.Equal(["2 Fast", "10 Things", "apple", "Banana"], NamesOf(new NameOrder().OrderBy(items)));
    }

    [Fact]
    public void OrderBy_Descending_KeepsInputOrderAmongEqualKeys()
    {
        // Descending is OrderByDescending on the same key, NOT a reversal of the ascending
        // result - so ties keep their incoming order in both directions.
        var first = NewMovie("Alpha", "same key");
        var second = NewMovie("Beta", "same key");
        var items = new BaseItem[] { first, second };

        Assert.Equal(["Alpha", "Beta"], NamesOf(new NameOrder().OrderBy(items)));
        Assert.Equal(["Alpha", "Beta"], NamesOf(new NameOrderDesc().OrderBy(items)));
    }

    [Fact]
    public void GetSortKey_NameOrderDescending_ReturnsTheSameKeyAsAscending()
    {
        // Direction is applied by the sorting pipeline, never by negating the key. If Desc
        // ever started returning an inverted key, multi-sort would double-invert it.
        var item = NewAudio("Track Name", "0001 - Track Name");

        Assert.Equal("Track Name", new NameOrder().GetSortKey(item, null!, null, null));
        Assert.Equal("Track Name", new NameOrderDesc().GetSortKey(item, null!, null, null));
    }

    // =================================================================================
    // NameIgnoreArticlesOrder - StripLeadingArticles
    // Only "the" is in the article list (a/an and the other languages are commented out in
    // OrderUtilities.Articles), and it only counts when followed by a space.
    // =================================================================================

    [Theory]
    [InlineData("The Matrix", "Matrix")]
    [InlineData("THE MATRIX", "MATRIX")]              // case-insensitive match
    [InlineData("the matrix", "matrix")]
    [InlineData("  The Matrix", "Matrix")]            // leading whitespace is trimmed first
    [InlineData("The Matrix  ", "Matrix")]            // trailing whitespace is trimmed too
    [InlineData("The   Matrix", "Matrix")]            // remainder is TrimStart'ed
    [InlineData("A Bug's Life", "A Bug's Life")]      // "a" is NOT an article here
    [InlineData("An Ant", "An Ant")]                  // "an" is NOT an article here
    [InlineData("The", "The")]                        // whole name is the article: no space
    [InlineData("Theater", "Theater")]                // prefix match must not be enough
    [InlineData("The-Matrix", "The-Matrix")]          // separator must be a space
    [InlineData("Le Fabuleux Destin", "Le Fabuleux Destin")]  // French article: not stripped
    [InlineData("Der Untergang", "Der Untergang")]            // German article: not stripped
    [InlineData("Det Sjunde Inseglet", "Det Sjunde Inseglet")] // Swedish: not stripped
    [InlineData("", "")]
    [InlineData("   ", "   ")]                        // whitespace-only is returned untouched
    public void ComputeNameIgnoreArticlesSortValue_StripsOnlyLeadingThe(string name, string expected)
    {
        var movie = NewMovie(name);

        Assert.Equal(expected, NameIgnoreArticlesOrder.ComputeNameIgnoreArticlesSortValue(movie));
    }

    [Fact]
    public void ComputeNameIgnoreArticlesSortValue_SortNamePresent_IsUsedVerbatimWithItsArticle()
    {
        // Deliberate: a manual sort title is the user's own answer, so articles are left alone.
        var withSortName = NewMovie("The Matrix", "The Matrix");
        var withoutSortName = NewMovie("The Matrix");

        Assert.Equal("The Matrix", NameIgnoreArticlesOrder.ComputeNameIgnoreArticlesSortValue(withSortName));
        Assert.Equal("Matrix", NameIgnoreArticlesOrder.ComputeNameIgnoreArticlesSortValue(withoutSortName));
    }

    [Theory]
    [InlineData("001 - 0001 - The Pilot", "Pilot")]        // auto-generated -> strip from Name
    [InlineData("0012 - 00034 - The Pilot", "Pilot")]      // 3+ / 4+ digits
    [InlineData("01 - 0001 - x", "01 - 0001 - x")]         // 2 digits: manual
    [InlineData("001 - 001 - x", "001 - 001 - x")]         // 3 digits in group 2: manual
    [InlineData("A", "A")]                                 // manual sort title wins
    [InlineData("", "Pilot")]                              // no sort name -> strip from Name
    public void ComputeNameIgnoreArticlesSortValue_Episode_StripsFromNameOnlyForAutoGeneratedSortNames(string sortName, string expected)
    {
        var episode = NewEpisode("The Pilot", sortName);

        Assert.Equal(expected, NameIgnoreArticlesOrder.ComputeNameIgnoreArticlesSortValue(episode));
    }

    [Fact(Skip = "suspected real bug: the two episode auto-sort-name detectors disagree. "
        + "NameSortHelper uses ^\\d{3,}\\s+-\\s+\\d{4,}\\s+-\\s+ (any whitespace run) while "
        + "NameIgnoreArticlesOrder uses ^\\d{3,} - \\d{4,} -  (literal single spaces). They are "
        + "meant to detect the same thing, so the same episode is 'auto-generated' to Name "
        + "Ascending and 'manual' to Name (Ignore Articles) Ascending. Fix by widening the "
        + "NameIgnoreArticlesOrder pattern to \\s+, then un-skip.")]
    public void ComputeNameIgnoreArticlesSortValue_EpisodePattern_AgreesWithNameSortHelper()
    {
        // Written to the intended behaviour: both detectors should recognise the same
        // auto-generated sort name and fall back to the item's Name.
        var episode = NewEpisode("The Pilot", "001  -  0001  -  The Pilot");

        Assert.Equal("The Pilot", NameSortHelper.GetNameSortValue(episode));
        Assert.Equal("Pilot", NameIgnoreArticlesOrder.ComputeNameIgnoreArticlesSortValue(episode));
    }

    [Fact]
    public void ComputeNameIgnoreArticlesSortValue_NullNameAndNullItem()
    {
        Assert.Equal("", NameIgnoreArticlesOrder.ComputeNameIgnoreArticlesSortValue(NewMovie(null)));
        Assert.Equal("", NameIgnoreArticlesOrder.ComputeNameIgnoreArticlesSortValue(NewEpisode(null, "001 - 0001 - x")));
        Assert.Throws<ArgumentNullException>(() => NameIgnoreArticlesOrder.ComputeNameIgnoreArticlesSortValue(null!));
    }

    [Fact]
    public void OrderBy_NameIgnoreArticles_SortsUnderTheStrippedName()
    {
        var items = new BaseItem[]
        {
            NewMovie("The Abyss"),
            NewMovie("Blade"),
            NewMovie("Zodiac"),
        };

        Assert.Equal(["The Abyss", "Blade", "Zodiac"], NamesOf(new NameIgnoreArticlesOrder().OrderBy(items)));
        Assert.Equal(["Zodiac", "Blade", "The Abyss"], NamesOf(new NameIgnoreArticlesOrderDesc().OrderBy(items)));

        // Same three items under plain Name Ascending: "The Abyss" sorts under T.
        Assert.Equal(["Blade", "The Abyss", "Zodiac"], NamesOf(new NameOrder().OrderBy(items)));
    }

    [Fact]
    public void GetSortKey_NameIgnoreArticlesDescending_ReturnsTheSameKeyAsAscending()
    {
        var item = NewMovie("The Matrix");

        Assert.Equal("Matrix", new NameIgnoreArticlesOrder().GetSortKey(item, null!, null, null));
        Assert.Equal("Matrix", new NameIgnoreArticlesOrderDesc().GetSortKey(item, null!, null, null));
    }

    // =================================================================================
    // SeriesNameOrder vs SeriesNameIgnoreArticlesOrder
    // The pair exists so users can pick "The IT Crowd" or "IT Crowd", so their cache
    // precedence is deliberately opposite:
    //   SeriesNameOrder              : SeriesNameById  -> SeriesSortNameById -> ...
    //   SeriesNameIgnoreArticlesOrder: SeriesSortNameById -> SeriesNameById(stripped) -> ...
    // =================================================================================

    private static string SeriesKey(BaseItem item, RefreshQueueService.RefreshCache? cache) =>
        (string)new SeriesNameOrder().GetSortKey(item, null!, null, null, null, cache);

    private static string SeriesIgnoreArticlesKey(BaseItem item, RefreshQueueService.RefreshCache? cache) =>
        (string)new SeriesNameIgnoreArticlesOrder().GetSortKey(item, null!, null, null, null, cache);

    [Fact]
    public void GetSortValue_BothCacheEntriesPresent_TheTwoSeriesOrdersDeliberatelyDisagree()
    {
        var seriesId = Guid.NewGuid();
        var cache = new RefreshQueueService.RefreshCache();
        cache.SeriesNameById[seriesId] = "The IT Crowd";
        cache.SeriesSortNameById[seriesId] = "IT Crowd, The";
        var episode = NewEpisode("Yesterday's Jam", sortName: "", seriesName: "ignored", seriesId: seriesId);

        Assert.Equal("The IT Crowd", SeriesKey(episode, cache));
        Assert.Equal("IT Crowd, The", SeriesIgnoreArticlesKey(episode, cache));
    }

    [Fact]
    public void GetSortValue_OnlyCachedSeriesName_IsStrippedByTheIgnoreArticlesVariantOnly()
    {
        var seriesId = Guid.NewGuid();
        var cache = new RefreshQueueService.RefreshCache();
        cache.SeriesNameById[seriesId] = "The IT Crowd";
        var episode = NewEpisode("Yesterday's Jam", sortName: "", seriesId: seriesId);

        Assert.Equal("The IT Crowd", SeriesKey(episode, cache));
        Assert.Equal("IT Crowd", SeriesIgnoreArticlesKey(episode, cache));
    }

    [Fact]
    public void GetSortValue_EmptyCachedSortName_IsSkippedRatherThanUsed()
    {
        // Both orders guard the SeriesSortNameById hit with !IsNullOrEmpty, so an empty cached
        // sort name must not collapse the key to "" (which would clump unrelated series).
        var seriesId = Guid.NewGuid();
        var cache = new RefreshQueueService.RefreshCache();
        cache.SeriesNameById[seriesId] = "The Wire";
        cache.SeriesSortNameById[seriesId] = "";
        var episode = NewEpisode("The Target", sortName: "", seriesId: seriesId);

        Assert.Equal("The Wire", SeriesKey(episode, cache));
        Assert.Equal("Wire", SeriesIgnoreArticlesKey(episode, cache));
    }

    /// <summary>
    /// SeriesNameOrder consults SeriesNameById first and only falls back to SeriesSortNameById on
    /// a miss. Every other test in this file populates SeriesNameById, so without this case the
    /// entire fallback branch is dead to the suite - verified by deleting it from production and
    /// watching everything stay green.
    /// </summary>
    [Fact]
    public void GetSortValue_SeriesSortNameCache_IsUsedWhenTheDisplayNameCacheMisses()
    {
        var seriesId = Guid.NewGuid();
        var cache = new RefreshQueueService.RefreshCache();
        // Deliberately NOT populating SeriesNameById.
        cache.SeriesSortNameById[seriesId] = "IT Crowd, The";
        var episode = NewEpisode("Yesterday's Jam", sortName: "", seriesId: seriesId);

        Assert.Equal("IT Crowd, The", SeriesKey(episode, cache));
    }

    /// <summary>
    /// Same miss, but the cached sort name is empty - the !IsNullOrEmpty guard must reject it and
    /// let resolution continue to the item's own properties rather than returning "".
    /// </summary>
    [Fact]
    public void GetSortValue_EmptySeriesSortNameCache_FallsThroughToItemProperties()
    {
        var seriesId = Guid.NewGuid();
        var cache = new RefreshQueueService.RefreshCache();
        cache.SeriesSortNameById[seriesId] = "";
        var episode = NewEpisode("Yesterday's Jam", sortName: "", seriesName: "The IT Crowd", seriesId: seriesId);

        Assert.Equal("The IT Crowd", SeriesKey(episode, cache));
    }

    [Fact]
    public void GetSortValue_EmptySeriesId_NeverConsultsTheCache()
    {
        // The cache is keyed by SeriesId; an episode that has none must not pick up whatever
        // happens to sit under Guid.Empty.
        var cache = new RefreshQueueService.RefreshCache();
        cache.SeriesNameById[Guid.Empty] = "Wrong Series";
        cache.SeriesSortNameById[Guid.Empty] = "Wrong Series Sort";
        var episode = NewEpisode("The Target", sortName: "", seriesName: "The Real Series");

        Assert.Equal(Guid.Empty, episode.SeriesId);
        Assert.Equal("The Real Series", SeriesKey(episode, cache));
        Assert.Equal("Real Series", SeriesIgnoreArticlesKey(episode, cache));
    }

    [Fact]
    public void GetSortValue_ItemSortName_WinsOverSeriesName_AndKeepsItsArticle()
    {
        // Fallback order once the cache misses: item.SortName, then the SeriesName property.
        // The ignore-articles variant uses SortName as-is, so "The" survives there too.
        var episode = NewEpisode("Pilot", sortName: "The Manual Title", seriesName: "Zeta Series");

        Assert.Equal("The Manual Title", SeriesKey(episode, null));
        Assert.Equal("The Manual Title", SeriesIgnoreArticlesKey(episode, null));
    }

    [Fact]
    public void GetSortValue_NoCacheAndNoSortName_ReadsSeriesNameByReflection()
    {
        var episode = NewEpisode("Pilot", sortName: "", seriesName: "The Wire");

        Assert.Equal("The Wire", SeriesKey(episode, null));
        Assert.Equal("Wire", SeriesIgnoreArticlesKey(episode, null));
    }

    [Fact]
    public void GetSortValue_ItemWithoutSeriesNameProperty_ReturnsEmptyString()
    {
        // A Movie has no SeriesName property, so the reflection lookup finds nothing.
        var movie = NewMovie("Casablanca");

        Assert.Equal("", SeriesKey(movie, new RefreshQueueService.RefreshCache()));
        Assert.Equal("", SeriesIgnoreArticlesKey(movie, null));
    }

    [Fact]
    public void GetSortValue_SeriesOrders_ThrowOnNullItem()
    {
        Assert.Throws<ArgumentNullException>(() => new SeriesNameOrder().GetSortKey(null!, null!, null, null));
        Assert.Throws<ArgumentNullException>(() => new SeriesNameOrderDesc().GetSortKey(null!, null!, null, null));
        Assert.Throws<ArgumentNullException>(
            () => SeriesNameIgnoreArticlesOrder.ComputeSeriesNameIgnoreArticlesSortValue(null!));
    }

    [Fact]
    public void GetSortKey_SeriesNameDescending_MatchesAscending_AcrossEveryFallbackBranch()
    {
        // SeriesNameOrderDesc re-implements the whole body of SeriesNameOrder instead of
        // sharing it, so the two can silently drift apart. This walks all four branches.
        var seriesId = Guid.NewGuid();
        var cache = new RefreshQueueService.RefreshCache();
        cache.SeriesNameById[seriesId] = "The IT Crowd";
        cache.SeriesSortNameById[seriesId] = "IT Crowd, The";

        BaseItem[] samples =
        [
            NewEpisode("Cached", sortName: "", seriesId: seriesId),                       // cache hit
            NewEpisode("SortName", sortName: "Manual", seriesName: "Series"),             // item.SortName
            NewEpisode("Reflected", sortName: "", seriesName: "The Wire"),                // reflection
            NewMovie("No Series"),                                                        // empty
        ];

        var asc = new SeriesNameOrder();
        var desc = new SeriesNameOrderDesc();
        foreach (var item in samples)
        {
            Assert.Equal(
                asc.GetSortKey(item, null!, null, null, null, cache),
                desc.GetSortKey(item, null!, null, null, null, cache));
        }

        var ascIgnore = new SeriesNameIgnoreArticlesOrder();
        var descIgnore = new SeriesNameIgnoreArticlesOrderDesc();
        foreach (var item in samples)
        {
            Assert.Equal(
                ascIgnore.GetSortKey(item, null!, null, null, null, cache),
                descIgnore.GetSortKey(item, null!, null, null, null, cache));
        }
    }

    [Fact]
    public void OrderBy_SeriesName_UsesTheCacheAndReversesUnderDescending()
    {
        var alien = Guid.NewGuid();
        var bosch = Guid.NewGuid();
        var cache = new RefreshQueueService.RefreshCache();
        cache.SeriesNameById[alien] = "The Alienist";
        cache.SeriesNameById[bosch] = "Bosch";

        var items = new BaseItem[]
        {
            NewEpisode("A1", sortName: "", seriesId: alien),
            NewEpisode("B1", sortName: "", seriesId: bosch),
        };

        // "Bosch" < "The Alienist" alphabetically...
        Assert.Equal(["B1", "A1"], NamesOf(new SeriesNameOrder().OrderBy(items, null!, null, null, cache)));
        Assert.Equal(["A1", "B1"], NamesOf(new SeriesNameOrderDesc().OrderBy(items, null!, null, null, cache)));

        // ...but "Alienist" < "Bosch" once the article is stripped.
        Assert.Equal(["A1", "B1"], NamesOf(new SeriesNameIgnoreArticlesOrder().OrderBy(items, null!, null, null, cache)));
        Assert.Equal(["B1", "A1"], NamesOf(new SeriesNameIgnoreArticlesOrderDesc().OrderBy(items, null!, null, null, cache)));
    }

    [Fact]
    public void OrderBy_SeriesName_WithoutTheCacheOverload_IgnoresTheCacheEntirely()
    {
        // The 1-argument OrderBy passes no RefreshCache, so cached series names are invisible
        // to it and only the item's own properties count.
        var seriesId = Guid.NewGuid();
        var cache = new RefreshQueueService.RefreshCache();
        cache.SeriesNameById[seriesId] = "Zzz Cached";
        var episode = NewEpisode("Pilot", sortName: "", seriesName: "Aaa Reflected", seriesId: seriesId);
        var other = NewEpisode("Other", sortName: "", seriesName: "Mmm Other");
        var items = new BaseItem[] { episode, other };

        Assert.Equal(["Pilot", "Other"], NamesOf(new SeriesNameOrder().OrderBy(items)));
        Assert.Equal(["Other", "Pilot"], NamesOf(new SeriesNameOrder().OrderBy(items, null!, null, null, cache)));
    }

    // =================================================================================
    // ArtistOrder - reflection on an "Artists" property, first entry only
    // =================================================================================

    [Fact]
    public void GetSortValue_Artist_UsesTheFirstListedArtistNotTheAlphabeticallyFirst()
    {
        var audio = NewAudio("Track", artists: ["Zed Leppelin", "Alpha Guest"]);

        Assert.Equal("Zed Leppelin", new ArtistOrder().GetSortKey(audio, null!, null, null));
        Assert.Equal("Zed Leppelin", new ArtistOrderDesc().GetSortKey(audio, null!, null, null));
    }

    [Fact]
    public void GetSortValue_Artist_ReturnsEmptyStringWhenThereIsNoArtist()
    {
        Assert.Equal("", new ArtistOrder().GetSortKey(NewAudio("Track", artists: []), null!, null, null));
        Assert.Equal("", new ArtistOrder().GetSortKey(NewMovie("Casablanca"), null!, null, null));
        Assert.Equal("", new ArtistOrderDesc().GetSortKey(NewMovie("Casablanca"), null!, null, null));
    }

    [Fact]
    public void GetSortValue_Artist_ThrowsOnNullItem()
    {
        Assert.Throws<ArgumentNullException>(() => new ArtistOrder().GetSortKey(null!, null!, null, null));
        Assert.Throws<ArgumentNullException>(() => new ArtistOrderDesc().GetSortKey(null!, null!, null, null));
    }

    [Fact]
    public void OrderBy_Artist_SortsByFirstArtist_AndPutsArtistlessItemsFirstAscending()
    {
        var items = new BaseItem[]
        {
            NewAudio("beta track", artists: ["beta artist"]),
            NewAudio("no artist"),
            NewAudio("alpha track", artists: ["Alpha Artist"]),
        };

        // The artistless item keys on "" and so leads ascending / trails descending, and the
        // comparison itself is case-insensitive ("Alpha Artist" before "beta artist").
        Assert.Equal(["no artist", "alpha track", "beta track"], NamesOf(new ArtistOrder().OrderBy(items)));
        Assert.Equal(["beta track", "alpha track", "no artist"], NamesOf(new ArtistOrderDesc().OrderBy(items)));
    }
}
